### ISSUE TITLE
Support JavaDoc plugin 3.5.0

### ISSUE THREAD

**Issue by fhoeben** [praegus/fixture-doc-generator#3]
Trying to upgrade JavaDoc plugin in my project (https://github.com/fhoeben/hsac-fitnesse-fixtures/pull/472) I ran into [the following error](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765):

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.5.0:javadoc (default) on project hsac-fitnesse-fixtures: An error has occurred in Javadoc report generation: 
[1555](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1556)
Error:  Exit code: 1
[1556](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1557)
Error: [ERROR] javadoc: error - In doclet class nl.praegus.doclets.FixtureDocGenerator,  method start has thrown an exception java.lang.reflect.InvocationTargetException
[1557](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1558)
Error:  java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
[1558](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1559)
Error:  	at nl.praegus.doclets.FixtureDocGenerator.writeJson(FixtureDocGenerator.java:197)
[1559](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1560)
Error:  	at nl.praegus.doclets.FixtureDocGenerator.parseClass(FixtureDocGenerator.java:72)
[1560](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1561)
Error:  	at nl.praegus.doclets.FixtureDocGenerator.start(FixtureDocGenerator.java:42)
[1561](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1562)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[1562](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1563)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[1563](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1564)
Error:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[1564](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1565)
Error:  	at java.lang.reflect.Method.invoke(Method.java:498)
[1565](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1566)
Error:  	at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
[1566](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1567)
Error:  	at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
[1567](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1568)
Error:  	at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
[1568](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1569)
Error:  	at com.sun.tools.javadoc.Start.begin(Start.java:219)
[1569](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1570)
Error:  	at com.sun.tools.javadoc.Start.begin(Start.java:205)
[1570](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1571)
Error:  	at com.sun.tools.javadoc.Main.execute(Main.java:64)
[1571](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1572)
Error:  	at com.sun.tools.javadoc.Main.main(Main.java:54)
[1572](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1573)
Error:  Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
[1573](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1574)
Error:  	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
[1574](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1575)
Error:  	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
[1575](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1576)
Error:  	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[1576](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1577)
Error:  	... 14 more
[1577](https://github.com/fhoeben/hsac-fitnesse-fixtures/actions/runs/4189911962/jobs/7262777765#step:4:1578)
Error:  Command line was: /opt/hostedtoolcache/Java_Zulu_jdk/8.0.362-9/x64/jre/../bin/javadoc @options @packages
```

**Comment by tcnh** [comment]
I'm afraid this is caused by https://issues.apache.org/jira/projects/MJAVADOC/issues/MJAVADOC-742
As long as there is no fix, no doclet can use any dependency whilst generating javadoc.

**Comment by fhoeben** [comment]
The linked issue seems closed. The last time I tried to generated JavaDoc locally I got the following errors. Any thoughts?

```
[INFO] --- maven-javadoc-plugin:3.4.1:javadoc (default) @ hsac-fitnesse-fixtures ---
[INFO] No previous run data found, generating javadoc.
[INFO] 
Loading source files for package nl.hsac.fitnesse.fixture.fit...
Loading source files for package nl.hsac.fitnesse.fixture.leanapps...
Loading source files for package nl.hsac.fitnesse.fixture.slim...
Loading source files for package nl.hsac.fitnesse.fixture.slim.web...
1 error


Exit code: 1 - javadoc: warning - The old Doclet and Taglet APIs in the packages
com.sun.javadoc, com.sun.tools.doclets and their implementations
are planned to be removed in a future JDK release. These
components have been superseded by the new APIs in jdk.javadoc.doclet.
Users are strongly recommended to migrate to the new APIs.
error: error reading /Users/fried/.m2/repository/org/seleniumhq/selenium/selenium-api/4.15.0/selenium-api-4.15.0.jar; zip file is empty

Command line was: /Users/fried/.sdkman/candidates/java/11.0.14-zulu/zulu-11.jdk/Contents/Home/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/Users/fried/dev/hsac-fitnesse-fixtures/src/main/resources/META-INF/apidocs' dir.


```

**Comment by tcnh** [comment]
Apart from the deprecation warning (doclet/taglet API's) I am able to generate the fixture doc json files from the javadoc generation using JDK11 and javadoc plugin 3.6.2 without errors (fixture-doc-generator 1.1) on the hsac-fitnesse-fixtures main branch.

**Comment by fhoeben** [comment]
Works for me now also. Turns out my download of selenium-api 4.15.0 was corrupted.
